project:
  type: website
  output-dir: ../docs
  render: 
    - "*.qmd"

format:
  html:
    theme: cosmo
    toc: true
    css: "styles.css"

editor: source

website:
  title: "BROKE-West fish to DwC-DP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/biodiversity-aq/broke-west-fish-dwc-dp
  page-navigation: true
  sidebar: 
    style: "docked"
    contents: 
      - section: Darwin Core Data Package
        contents:
          - href: generate-dwc-dp.qmd
            text: Generate tables for DwC-DP
          - href: explore-dwc-dp.qmd
            text: Exploring DwC-DP

